const colleges = [
    {
        "id": 1,
        "name": "Princeton University",
        "street": "1 Nassau Hall",
        "city": "Princeton",
        "state": "NJ",
        "zip": "08544",
        "tuition": 16192,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "Princeton.png",
        "url": "princeton.edu"
    },
    {
        "id": 2,
        "name": "Stevens Institute of Technology",
        "street": "1 Castle Point Terrace",
        "city": "Hoboken",
        "state": "NJ",
        "zip": "08822",
        "tuition": 39862,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "stevens.png",
        "url": "stevens.edu"
    },
    {
        "id": 3,
        "name": "Rutgers University - New Brunswick",
        "street": "100 Sutphen Road",
        "city": "Piscataway",
        "state": "NJ",
        "zip": "08854",
        "tuition": 16295,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "newbrunswick.rutgers.edu"
    },
    {
        "id": 4,
        "name": "The College of New Jersey",
        "street": "2000 Pennington Road",
        "city": "Ewing",
        "state": "NJ",
        "zip": "08628",
        "tuition": 23414,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "tcnj.edu"
    },
    {
        "id": 5,
        "name": "Rutgers University - Newark",
        "street": "249 University Avenue, Blumenthal Hall",
        "city": "Newark",
        "state": "NJ",
        "zip": "07102",
        "tuition": 11301,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "newark.rutgers.edu"
    },
   
    {
        "id": 6,
        "name": "Seton Hall University",
        "street": "400 S Orange Ave",
        "city": "South Orange",
        "state": "NJ",
        "zip": "07079",
        "tuition": 29974,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "shu.edu"
    },
    {
        "id": 7,
        "name": "New Jersey Institute of Technology",
        "street": "University Heights",
        "city": "Newark",
        "state": "NJ",
        "zip": "07102",
        "tuition": 17855,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "njit.edu"
    },
    {
        "id": 8,
        "name": "Drew University",
        "street": "36 Madison Ave",
        "city": "Madison",
        "state": "NJ",
        "zip": "07940",
        "tuition": 28993,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "drew.edu"
    },
    {
        "id": 9,
        "name": "Rutgers University - Camden",
        "street": "406 Penn Street Suite 305",
        "city": "Camden",
        "state": "NJ",
        "zip": "08102",
        "tuition": 12279,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "camden.rutgers.edu"
    },
    {
        "id": 10,
        "name": "Columbia University",
        "street": "West 116 St and Broadway",
        "city": "New York",
        "state": "NY",
        "zip": "10027",
        "tuition": 21220,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "columbia.edu"
    },
    {
        "id": 11,
        "name": "Barnard College",
        "street": "3009 Broadway",
        "city": "New York",
        "state": "NY",
        "zip": "10027",
        "tuition": 26681,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "barnard.edu"
    }, 
    {
        "id": 12,
        "name": "New York University",
        "street": "70 Washington Sq South",
        "city": "New York",
        "state": "NY",
        "zip": "10012",
        "tuition": 39935,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "nyu.edu"
    },
    
    {
        "id": 13,
        "name": "Cornell University",
        "street": "300 Day Hall",
        "city": "Ithaca",
        "state": "NY",
        "zip": "10027",
        "tuition": 28890,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "cornell.edu"
    },
    {
        "id": 14,
        "name": "Hamilton College",
        "street": "198 College Hill Road",
        "city": "Clinton",
        "state": "NY",
        "zip": "13323",
        "tuition": 27809,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "hamilton.edu"
    },
    {
        "id": 15,
        "name": "University of Rochester",
        "street": "Joseph C Wilson Blvd.",
        "city": "Rochester",
        "state": "NY",
        "zip": "14627",
        "tuition": 35452,
        "posts": [],
        "preferredAreas": [], 
        "avgExpense": 0,
        "logo": "rutgers.png",
        "url": "rochester.edu"
    }
    
    

];